/* 
 * IMDb-API
 *
 * The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>
 *
 * OpenAPI spec version: 1.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.TVSeries.Client.SwaggerDateConverter;

namespace IO.TVSeries.Model
{
    /// <summary>
    /// EpisodeShortDetail
    /// </summary>
    [DataContract]
        public partial class EpisodeShortDetail :  IEquatable<EpisodeShortDetail>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EpisodeShortDetail" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="seasonNumber">seasonNumber.</param>
        /// <param name="episodeNumber">episodeNumber.</param>
        /// <param name="title">title.</param>
        /// <param name="image">image.</param>
        /// <param name="year">year.</param>
        /// <param name="released">released.</param>
        /// <param name="plot">plot.</param>
        /// <param name="imDbRating">imDbRating.</param>
        /// <param name="imDbRatingCount">imDbRatingCount.</param>
        public EpisodeShortDetail(string id = default(string), string seasonNumber = default(string), string episodeNumber = default(string), string title = default(string), string image = default(string), string year = default(string), string released = default(string), string plot = default(string), string imDbRating = default(string), string imDbRatingCount = default(string))
        {
            this.Id = id;
            this.SeasonNumber = seasonNumber;
            this.EpisodeNumber = episodeNumber;
            this.Title = title;
            this.Image = image;
            this.Year = year;
            this.Released = released;
            this.Plot = plot;
            this.ImDbRating = imDbRating;
            this.ImDbRatingCount = imDbRatingCount;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets SeasonNumber
        /// </summary>
        [DataMember(Name="seasonNumber", EmitDefaultValue=false)]
        public string SeasonNumber { get; set; }

        /// <summary>
        /// Gets or Sets EpisodeNumber
        /// </summary>
        [DataMember(Name="episodeNumber", EmitDefaultValue=false)]
        public string EpisodeNumber { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets Image
        /// </summary>
        [DataMember(Name="image", EmitDefaultValue=false)]
        public string Image { get; set; }

        /// <summary>
        /// Gets or Sets Year
        /// </summary>
        [DataMember(Name="year", EmitDefaultValue=false)]
        public string Year { get; set; }

        /// <summary>
        /// Gets or Sets Released
        /// </summary>
        [DataMember(Name="released", EmitDefaultValue=false)]
        public string Released { get; set; }

        /// <summary>
        /// Gets or Sets Plot
        /// </summary>
        [DataMember(Name="plot", EmitDefaultValue=false)]
        public string Plot { get; set; }

        /// <summary>
        /// Gets or Sets ImDbRating
        /// </summary>
        [DataMember(Name="imDbRating", EmitDefaultValue=false)]
        public string ImDbRating { get; set; }

        /// <summary>
        /// Gets or Sets ImDbRatingCount
        /// </summary>
        [DataMember(Name="imDbRatingCount", EmitDefaultValue=false)]
        public string ImDbRatingCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EpisodeShortDetail {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  SeasonNumber: ").Append(SeasonNumber).Append("\n");
            sb.Append("  EpisodeNumber: ").Append(EpisodeNumber).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Image: ").Append(Image).Append("\n");
            sb.Append("  Year: ").Append(Year).Append("\n");
            sb.Append("  Released: ").Append(Released).Append("\n");
            sb.Append("  Plot: ").Append(Plot).Append("\n");
            sb.Append("  ImDbRating: ").Append(ImDbRating).Append("\n");
            sb.Append("  ImDbRatingCount: ").Append(ImDbRatingCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EpisodeShortDetail);
        }

        /// <summary>
        /// Returns true if EpisodeShortDetail instances are equal
        /// </summary>
        /// <param name="input">Instance of EpisodeShortDetail to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EpisodeShortDetail input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.SeasonNumber == input.SeasonNumber ||
                    (this.SeasonNumber != null &&
                    this.SeasonNumber.Equals(input.SeasonNumber))
                ) && 
                (
                    this.EpisodeNumber == input.EpisodeNumber ||
                    (this.EpisodeNumber != null &&
                    this.EpisodeNumber.Equals(input.EpisodeNumber))
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.Image == input.Image ||
                    (this.Image != null &&
                    this.Image.Equals(input.Image))
                ) && 
                (
                    this.Year == input.Year ||
                    (this.Year != null &&
                    this.Year.Equals(input.Year))
                ) && 
                (
                    this.Released == input.Released ||
                    (this.Released != null &&
                    this.Released.Equals(input.Released))
                ) && 
                (
                    this.Plot == input.Plot ||
                    (this.Plot != null &&
                    this.Plot.Equals(input.Plot))
                ) && 
                (
                    this.ImDbRating == input.ImDbRating ||
                    (this.ImDbRating != null &&
                    this.ImDbRating.Equals(input.ImDbRating))
                ) && 
                (
                    this.ImDbRatingCount == input.ImDbRatingCount ||
                    (this.ImDbRatingCount != null &&
                    this.ImDbRatingCount.Equals(input.ImDbRatingCount))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.SeasonNumber != null)
                    hashCode = hashCode * 59 + this.SeasonNumber.GetHashCode();
                if (this.EpisodeNumber != null)
                    hashCode = hashCode * 59 + this.EpisodeNumber.GetHashCode();
                if (this.Title != null)
                    hashCode = hashCode * 59 + this.Title.GetHashCode();
                if (this.Image != null)
                    hashCode = hashCode * 59 + this.Image.GetHashCode();
                if (this.Year != null)
                    hashCode = hashCode * 59 + this.Year.GetHashCode();
                if (this.Released != null)
                    hashCode = hashCode * 59 + this.Released.GetHashCode();
                if (this.Plot != null)
                    hashCode = hashCode * 59 + this.Plot.GetHashCode();
                if (this.ImDbRating != null)
                    hashCode = hashCode * 59 + this.ImDbRating.GetHashCode();
                if (this.ImDbRatingCount != null)
                    hashCode = hashCode * 59 + this.ImDbRatingCount.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
