/* 
 * IMDb-API
 *
 * The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>
 *
 * OpenAPI spec version: 1.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
//using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AwardOutcomeDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AwardOutcomeDetailTests
    {
        // TODO uncomment below to declare an instance variable for AwardOutcomeDetail
        //private AwardOutcomeDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AwardOutcomeDetail
            //instance = new AwardOutcomeDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AwardOutcomeDetail
        /// </summary>
        [Test]
        public void AwardOutcomeDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AwardOutcomeDetail
            //Assert.IsInstanceOfType<AwardOutcomeDetail> (instance, "variable 'instance' is a AwardOutcomeDetail");
        }


        /// <summary>
        /// Test the property 'PlainText'
        /// </summary>
        [Test]
        public void PlainTextTest()
        {
            // TODO unit test for the property 'PlainText'
        }
        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Test]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }

    }

}
