/* 
 * IMDb-API
 *
 * The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>
 *
 * OpenAPI spec version: 1.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
//using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BoxOfficeWeekendDataDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BoxOfficeWeekendDataDetailTests
    {
        // TODO uncomment below to declare an instance variable for BoxOfficeWeekendDataDetail
        //private BoxOfficeWeekendDataDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BoxOfficeWeekendDataDetail
            //instance = new BoxOfficeWeekendDataDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BoxOfficeWeekendDataDetail
        /// </summary>
        [Test]
        public void BoxOfficeWeekendDataDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BoxOfficeWeekendDataDetail
            //Assert.IsInstanceOfType<BoxOfficeWeekendDataDetail> (instance, "variable 'instance' is a BoxOfficeWeekendDataDetail");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Rank'
        /// </summary>
        [Test]
        public void RankTest()
        {
            // TODO unit test for the property 'Rank'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'Weekend'
        /// </summary>
        [Test]
        public void WeekendTest()
        {
            // TODO unit test for the property 'Weekend'
        }
        /// <summary>
        /// Test the property 'Gross'
        /// </summary>
        [Test]
        public void GrossTest()
        {
            // TODO unit test for the property 'Gross'
        }
        /// <summary>
        /// Test the property 'Weeks'
        /// </summary>
        [Test]
        public void WeeksTest()
        {
            // TODO unit test for the property 'Weeks'
        }

    }

}
