/* 
 * IMDb-API
 *
 * The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>
 *
 * OpenAPI spec version: 1.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
//using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EpisodeShortDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EpisodeShortDetailTests
    {
        // TODO uncomment below to declare an instance variable for EpisodeShortDetail
        //private EpisodeShortDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EpisodeShortDetail
            //instance = new EpisodeShortDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EpisodeShortDetail
        /// </summary>
        [Test]
        public void EpisodeShortDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EpisodeShortDetail
            //Assert.IsInstanceOfType<EpisodeShortDetail> (instance, "variable 'instance' is a EpisodeShortDetail");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'SeasonNumber'
        /// </summary>
        [Test]
        public void SeasonNumberTest()
        {
            // TODO unit test for the property 'SeasonNumber'
        }
        /// <summary>
        /// Test the property 'EpisodeNumber'
        /// </summary>
        [Test]
        public void EpisodeNumberTest()
        {
            // TODO unit test for the property 'EpisodeNumber'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Test]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'Released'
        /// </summary>
        [Test]
        public void ReleasedTest()
        {
            // TODO unit test for the property 'Released'
        }
        /// <summary>
        /// Test the property 'Plot'
        /// </summary>
        [Test]
        public void PlotTest()
        {
            // TODO unit test for the property 'Plot'
        }
        /// <summary>
        /// Test the property 'ImDbRating'
        /// </summary>
        [Test]
        public void ImDbRatingTest()
        {
            // TODO unit test for the property 'ImDbRating'
        }
        /// <summary>
        /// Test the property 'ImDbRatingCount'
        /// </summary>
        [Test]
        public void ImDbRatingCountTest()
        {
            // TODO unit test for the property 'ImDbRatingCount'
        }

    }

}
