/* 
 * IMDb-API
 *
 * The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>
 *
 * OpenAPI spec version: 1.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
//using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExternalSiteData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExternalSiteDataTests
    {
        // TODO uncomment below to declare an instance variable for ExternalSiteData
        //private ExternalSiteData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExternalSiteData
            //instance = new ExternalSiteData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExternalSiteData
        /// </summary>
        [Test]
        public void ExternalSiteDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExternalSiteData
            //Assert.IsInstanceOfType<ExternalSiteData> (instance, "variable 'instance' is a ExternalSiteData");
        }


        /// <summary>
        /// Test the property 'ImDbId'
        /// </summary>
        [Test]
        public void ImDbIdTest()
        {
            // TODO unit test for the property 'ImDbId'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'FullTitle'
        /// </summary>
        [Test]
        public void FullTitleTest()
        {
            // TODO unit test for the property 'FullTitle'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Test]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'OfficialWebsite'
        /// </summary>
        [Test]
        public void OfficialWebsiteTest()
        {
            // TODO unit test for the property 'OfficialWebsite'
        }
        /// <summary>
        /// Test the property 'ImDb'
        /// </summary>
        [Test]
        public void ImDbTest()
        {
            // TODO unit test for the property 'ImDb'
        }
        /// <summary>
        /// Test the property 'TheMovieDb'
        /// </summary>
        [Test]
        public void TheMovieDbTest()
        {
            // TODO unit test for the property 'TheMovieDb'
        }
        /// <summary>
        /// Test the property 'RottenTomatoes'
        /// </summary>
        [Test]
        public void RottenTomatoesTest()
        {
            // TODO unit test for the property 'RottenTomatoes'
        }
        /// <summary>
        /// Test the property 'Metacritic'
        /// </summary>
        [Test]
        public void MetacriticTest()
        {
            // TODO unit test for the property 'Metacritic'
        }
        /// <summary>
        /// Test the property 'Netflix'
        /// </summary>
        [Test]
        public void NetflixTest()
        {
            // TODO unit test for the property 'Netflix'
        }
        /// <summary>
        /// Test the property 'GooglePlay'
        /// </summary>
        [Test]
        public void GooglePlayTest()
        {
            // TODO unit test for the property 'GooglePlay'
        }
        /// <summary>
        /// Test the property 'FilmAffinity'
        /// </summary>
        [Test]
        public void FilmAffinityTest()
        {
            // TODO unit test for the property 'FilmAffinity'
        }
        /// <summary>
        /// Test the property 'Freebase'
        /// </summary>
        [Test]
        public void FreebaseTest()
        {
            // TODO unit test for the property 'Freebase'
        }
        /// <summary>
        /// Test the property 'Gnd'
        /// </summary>
        [Test]
        public void GndTest()
        {
            // TODO unit test for the property 'Gnd'
        }
        /// <summary>
        /// Test the property 'Viaf'
        /// </summary>
        [Test]
        public void ViafTest()
        {
            // TODO unit test for the property 'Viaf'
        }
        /// <summary>
        /// Test the property 'AlloCine'
        /// </summary>
        [Test]
        public void AlloCineTest()
        {
            // TODO unit test for the property 'AlloCine'
        }
        /// <summary>
        /// Test the property 'AllMovie'
        /// </summary>
        [Test]
        public void AllMovieTest()
        {
            // TODO unit test for the property 'AllMovie'
        }
        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Test]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }
        /// <summary>
        /// Test the property 'Dnf'
        /// </summary>
        [Test]
        public void DnfTest()
        {
            // TODO unit test for the property 'Dnf'
        }
        /// <summary>
        /// Test the property 'MovieMeter'
        /// </summary>
        [Test]
        public void MovieMeterTest()
        {
            // TODO unit test for the property 'MovieMeter'
        }
        /// <summary>
        /// Test the property 'BoxOfficeMojo'
        /// </summary>
        [Test]
        public void BoxOfficeMojoTest()
        {
            // TODO unit test for the property 'BoxOfficeMojo'
        }
        /// <summary>
        /// Test the property 'Csfd'
        /// </summary>
        [Test]
        public void CsfdTest()
        {
            // TODO unit test for the property 'Csfd'
        }
        /// <summary>
        /// Test the property 'Kinenote'
        /// </summary>
        [Test]
        public void KinenoteTest()
        {
            // TODO unit test for the property 'Kinenote'
        }
        /// <summary>
        /// Test the property 'Allcinema'
        /// </summary>
        [Test]
        public void AllcinemaTest()
        {
            // TODO unit test for the property 'Allcinema'
        }
        /// <summary>
        /// Test the property 'Kinopoisk'
        /// </summary>
        [Test]
        public void KinopoiskTest()
        {
            // TODO unit test for the property 'Kinopoisk'
        }
        /// <summary>
        /// Test the property 'Elonet'
        /// </summary>
        [Test]
        public void ElonetTest()
        {
            // TODO unit test for the property 'Elonet'
        }
        /// <summary>
        /// Test the property 'LdiF'
        /// </summary>
        [Test]
        public void LdiFTest()
        {
            // TODO unit test for the property 'LdiF'
        }
        /// <summary>
        /// Test the property 'Cineplex'
        /// </summary>
        [Test]
        public void CineplexTest()
        {
            // TODO unit test for the property 'Cineplex'
        }
        /// <summary>
        /// Test the property 'EDb'
        /// </summary>
        [Test]
        public void EDbTest()
        {
            // TODO unit test for the property 'EDb'
        }
        /// <summary>
        /// Test the property 'ElCinema'
        /// </summary>
        [Test]
        public void ElCinemaTest()
        {
            // TODO unit test for the property 'ElCinema'
        }
        /// <summary>
        /// Test the property 'ScopeDk'
        /// </summary>
        [Test]
        public void ScopeDkTest()
        {
            // TODO unit test for the property 'ScopeDk'
        }
        /// <summary>
        /// Test the property 'SwedishFilmDatabaseFilm'
        /// </summary>
        [Test]
        public void SwedishFilmDatabaseFilmTest()
        {
            // TODO unit test for the property 'SwedishFilmDatabaseFilm'
        }
        /// <summary>
        /// Test the property 'ElFilm'
        /// </summary>
        [Test]
        public void ElFilmTest()
        {
            // TODO unit test for the property 'ElFilm'
        }
        /// <summary>
        /// Test the property 'OfDb'
        /// </summary>
        [Test]
        public void OfDbTest()
        {
            // TODO unit test for the property 'OfDb'
        }
        /// <summary>
        /// Test the property 'OpenMediaDatabase'
        /// </summary>
        [Test]
        public void OpenMediaDatabaseTest()
        {
            // TODO unit test for the property 'OpenMediaDatabase'
        }
        /// <summary>
        /// Test the property 'QuoraTopic'
        /// </summary>
        [Test]
        public void QuoraTopicTest()
        {
            // TODO unit test for the property 'QuoraTopic'
        }
        /// <summary>
        /// Test the property 'CinemaDe'
        /// </summary>
        [Test]
        public void CinemaDeTest()
        {
            // TODO unit test for the property 'CinemaDe'
        }
        /// <summary>
        /// Test the property 'DeutscheSynchronkartei'
        /// </summary>
        [Test]
        public void DeutscheSynchronkarteiTest()
        {
            // TODO unit test for the property 'DeutscheSynchronkartei'
        }
        /// <summary>
        /// Test the property 'MovieWalker'
        /// </summary>
        [Test]
        public void MovieWalkerTest()
        {
            // TODO unit test for the property 'MovieWalker'
        }
        /// <summary>
        /// Test the property 'TvGuide'
        /// </summary>
        [Test]
        public void TvGuideTest()
        {
            // TODO unit test for the property 'TvGuide'
        }
        /// <summary>
        /// Test the property 'FilmwebPl'
        /// </summary>
        [Test]
        public void FilmwebPlTest()
        {
            // TODO unit test for the property 'FilmwebPl'
        }
        /// <summary>
        /// Test the property 'Isan'
        /// </summary>
        [Test]
        public void IsanTest()
        {
            // TODO unit test for the property 'Isan'
        }
        /// <summary>
        /// Test the property 'Eidr'
        /// </summary>
        [Test]
        public void EidrTest()
        {
            // TODO unit test for the property 'Eidr'
        }
        /// <summary>
        /// Test the property 'AfiCatalogOfFeature'
        /// </summary>
        [Test]
        public void AfiCatalogOfFeatureTest()
        {
            // TODO unit test for the property 'AfiCatalogOfFeature'
        }
        /// <summary>
        /// Test the property 'TheNumbers'
        /// </summary>
        [Test]
        public void TheNumbersTest()
        {
            // TODO unit test for the property 'TheNumbers'
        }
        /// <summary>
        /// Test the property 'TcmMovieDatabase'
        /// </summary>
        [Test]
        public void TcmMovieDatabaseTest()
        {
            // TODO unit test for the property 'TcmMovieDatabase'
        }
        /// <summary>
        /// Test the property 'CineGr'
        /// </summary>
        [Test]
        public void CineGrTest()
        {
            // TODO unit test for the property 'CineGr'
        }
        /// <summary>
        /// Test the property 'BfiNationalArchive'
        /// </summary>
        [Test]
        public void BfiNationalArchiveTest()
        {
            // TODO unit test for the property 'BfiNationalArchive'
        }
        /// <summary>
        /// Test the property 'ExploitationVisa'
        /// </summary>
        [Test]
        public void ExploitationVisaTest()
        {
            // TODO unit test for the property 'ExploitationVisa'
        }
        /// <summary>
        /// Test the property 'Sratim'
        /// </summary>
        [Test]
        public void SratimTest()
        {
            // TODO unit test for the property 'Sratim'
        }
        /// <summary>
        /// Test the property 'CineRessources'
        /// </summary>
        [Test]
        public void CineRessourcesTest()
        {
            // TODO unit test for the property 'CineRessources'
        }
        /// <summary>
        /// Test the property 'CinemathequeQuebecoise'
        /// </summary>
        [Test]
        public void CinemathequeQuebecoiseTest()
        {
            // TODO unit test for the property 'CinemathequeQuebecoise'
        }
        /// <summary>
        /// Test the property 'EncyclopaediaBritannicaOnline'
        /// </summary>
        [Test]
        public void EncyclopaediaBritannicaOnlineTest()
        {
            // TODO unit test for the property 'EncyclopaediaBritannicaOnline'
        }
        /// <summary>
        /// Test the property 'BechdelTestMovieList'
        /// </summary>
        [Test]
        public void BechdelTestMovieListTest()
        {
            // TODO unit test for the property 'BechdelTestMovieList'
        }
        /// <summary>
        /// Test the property 'MovieplayerIt'
        /// </summary>
        [Test]
        public void MovieplayerItTest()
        {
            // TODO unit test for the property 'MovieplayerIt'
        }
        /// <summary>
        /// Test the property 'MYmovies'
        /// </summary>
        [Test]
        public void MYmoviesTest()
        {
            // TODO unit test for the property 'MYmovies'
        }
        /// <summary>
        /// Test the property 'Cinematografo'
        /// </summary>
        [Test]
        public void CinematografoTest()
        {
            // TODO unit test for the property 'Cinematografo'
        }
        /// <summary>
        /// Test the property 'Lumiere'
        /// </summary>
        [Test]
        public void LumiereTest()
        {
            // TODO unit test for the property 'Lumiere'
        }
        /// <summary>
        /// Test the property 'Bfi'
        /// </summary>
        [Test]
        public void BfiTest()
        {
            // TODO unit test for the property 'Bfi'
        }
        /// <summary>
        /// Test the property 'Prisma'
        /// </summary>
        [Test]
        public void PrismaTest()
        {
            // TODO unit test for the property 'Prisma'
        }
        /// <summary>
        /// Test the property 'CineMagia'
        /// </summary>
        [Test]
        public void CineMagiaTest()
        {
            // TODO unit test for the property 'CineMagia'
        }
        /// <summary>
        /// Test the property 'Daum'
        /// </summary>
        [Test]
        public void DaumTest()
        {
            // TODO unit test for the property 'Daum'
        }
        /// <summary>
        /// Test the property 'Douban'
        /// </summary>
        [Test]
        public void DoubanTest()
        {
            // TODO unit test for the property 'Douban'
        }
        /// <summary>
        /// Test the property 'MuseumOfModernArt'
        /// </summary>
        [Test]
        public void MuseumOfModernArtTest()
        {
            // TODO unit test for the property 'MuseumOfModernArt'
        }
        /// <summary>
        /// Test the property 'IlMondoDeiDoppiatori'
        /// </summary>
        [Test]
        public void IlMondoDeiDoppiatoriTest()
        {
            // TODO unit test for the property 'IlMondoDeiDoppiatori'
        }
        /// <summary>
        /// Test the property 'Fandango'
        /// </summary>
        [Test]
        public void FandangoTest()
        {
            // TODO unit test for the property 'Fandango'
        }
        /// <summary>
        /// Test the property 'MoviepilotDe'
        /// </summary>
        [Test]
        public void MoviepilotDeTest()
        {
            // TODO unit test for the property 'MoviepilotDe'
        }
        /// <summary>
        /// Test the property 'SudocAuthorities'
        /// </summary>
        [Test]
        public void SudocAuthoritiesTest()
        {
            // TODO unit test for the property 'SudocAuthorities'
        }
        /// <summary>
        /// Test the property 'BibliothequeNationaleDeFrance'
        /// </summary>
        [Test]
        public void BibliothequeNationaleDeFranceTest()
        {
            // TODO unit test for the property 'BibliothequeNationaleDeFrance'
        }
        /// <summary>
        /// Test the property 'Siamzone'
        /// </summary>
        [Test]
        public void SiamzoneTest()
        {
            // TODO unit test for the property 'Siamzone'
        }
        /// <summary>
        /// Test the property 'AcademyAwardsDatabase'
        /// </summary>
        [Test]
        public void AcademyAwardsDatabaseTest()
        {
            // TODO unit test for the property 'AcademyAwardsDatabase'
        }
        /// <summary>
        /// Test the property 'KnowYourMeme'
        /// </summary>
        [Test]
        public void KnowYourMemeTest()
        {
            // TODO unit test for the property 'KnowYourMeme'
        }
        /// <summary>
        /// Test the property 'TheEncyclopediaOfScienceFiction'
        /// </summary>
        [Test]
        public void TheEncyclopediaOfScienceFictionTest()
        {
            // TODO unit test for the property 'TheEncyclopediaOfScienceFiction'
        }
        /// <summary>
        /// Test the property 'Letterboxd'
        /// </summary>
        [Test]
        public void LetterboxdTest()
        {
            // TODO unit test for the property 'Letterboxd'
        }
        /// <summary>
        /// Test the property 'ComicVine'
        /// </summary>
        [Test]
        public void ComicVineTest()
        {
            // TODO unit test for the property 'ComicVine'
        }
        /// <summary>
        /// Test the property 'TheTVDB'
        /// </summary>
        [Test]
        public void TheTVDBTest()
        {
            // TODO unit test for the property 'TheTVDB'
        }
        /// <summary>
        /// Test the property 'TvSpielfilmSeries'
        /// </summary>
        [Test]
        public void TvSpielfilmSeriesTest()
        {
            // TODO unit test for the property 'TvSpielfilmSeries'
        }
        /// <summary>
        /// Test the property 'WikipediaUrls'
        /// </summary>
        [Test]
        public void WikipediaUrlsTest()
        {
            // TODO unit test for the property 'WikipediaUrls'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }

    }

}
