/* 
 * IMDb-API
 *
 * The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>
 *
 * OpenAPI spec version: 1.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
//using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MetacriticReviewDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MetacriticReviewDetailTests
    {
        // TODO uncomment below to declare an instance variable for MetacriticReviewDetail
        //private MetacriticReviewDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MetacriticReviewDetail
            //instance = new MetacriticReviewDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MetacriticReviewDetail
        /// </summary>
        [Test]
        public void MetacriticReviewDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MetacriticReviewDetail
            //Assert.IsInstanceOfType<MetacriticReviewDetail> (instance, "variable 'instance' is a MetacriticReviewDetail");
        }


        /// <summary>
        /// Test the property 'Publisher'
        /// </summary>
        [Test]
        public void PublisherTest()
        {
            // TODO unit test for the property 'Publisher'
        }
        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Test]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }
        /// <summary>
        /// Test the property 'Link'
        /// </summary>
        [Test]
        public void LinkTest()
        {
            // TODO unit test for the property 'Link'
        }
        /// <summary>
        /// Test the property 'Rate'
        /// </summary>
        [Test]
        public void RateTest()
        {
            // TODO unit test for the property 'Rate'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

    }

}
