/* 
 * IMDb-API
 *
 * The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>
 *
 * OpenAPI spec version: 1.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
//using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NameAwardOutcome
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NameAwardOutcomeTests
    {
        // TODO uncomment below to declare an instance variable for NameAwardOutcome
        //private NameAwardOutcome instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NameAwardOutcome
            //instance = new NameAwardOutcome();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NameAwardOutcome
        /// </summary>
        [Test]
        public void NameAwardOutcomeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NameAwardOutcome
            //Assert.IsInstanceOfType<NameAwardOutcome> (instance, "variable 'instance' is a NameAwardOutcome");
        }


        /// <summary>
        /// Test the property 'OutcomeYear'
        /// </summary>
        [Test]
        public void OutcomeYearTest()
        {
            // TODO unit test for the property 'OutcomeYear'
        }
        /// <summary>
        /// Test the property 'OutcomeTitle'
        /// </summary>
        [Test]
        public void OutcomeTitleTest()
        {
            // TODO unit test for the property 'OutcomeTitle'
        }
        /// <summary>
        /// Test the property 'OutcomeCategory'
        /// </summary>
        [Test]
        public void OutcomeCategoryTest()
        {
            // TODO unit test for the property 'OutcomeCategory'
        }
        /// <summary>
        /// Test the property 'OutcomeDetails'
        /// </summary>
        [Test]
        public void OutcomeDetailsTest()
        {
            // TODO unit test for the property 'OutcomeDetails'
        }

    }

}
