/* 
 * IMDb-API
 *
 * The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>
 *
 * OpenAPI spec version: 1.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
//using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NewMovieDataDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NewMovieDataDetailTests
    {
        // TODO uncomment below to declare an instance variable for NewMovieDataDetail
        //private NewMovieDataDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NewMovieDataDetail
            //instance = new NewMovieDataDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewMovieDataDetail
        /// </summary>
        [Test]
        public void NewMovieDataDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewMovieDataDetail
            //Assert.IsInstanceOfType<NewMovieDataDetail> (instance, "variable 'instance' is a NewMovieDataDetail");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'FullTitle'
        /// </summary>
        [Test]
        public void FullTitleTest()
        {
            // TODO unit test for the property 'FullTitle'
        }
        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Test]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'ReleaseState'
        /// </summary>
        [Test]
        public void ReleaseStateTest()
        {
            // TODO unit test for the property 'ReleaseState'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'RuntimeMins'
        /// </summary>
        [Test]
        public void RuntimeMinsTest()
        {
            // TODO unit test for the property 'RuntimeMins'
        }
        /// <summary>
        /// Test the property 'RuntimeStr'
        /// </summary>
        [Test]
        public void RuntimeStrTest()
        {
            // TODO unit test for the property 'RuntimeStr'
        }
        /// <summary>
        /// Test the property 'Plot'
        /// </summary>
        [Test]
        public void PlotTest()
        {
            // TODO unit test for the property 'Plot'
        }
        /// <summary>
        /// Test the property 'ContentRating'
        /// </summary>
        [Test]
        public void ContentRatingTest()
        {
            // TODO unit test for the property 'ContentRating'
        }
        /// <summary>
        /// Test the property 'ImDbRating'
        /// </summary>
        [Test]
        public void ImDbRatingTest()
        {
            // TODO unit test for the property 'ImDbRating'
        }
        /// <summary>
        /// Test the property 'ImDbRatingCount'
        /// </summary>
        [Test]
        public void ImDbRatingCountTest()
        {
            // TODO unit test for the property 'ImDbRatingCount'
        }
        /// <summary>
        /// Test the property 'MetacriticRating'
        /// </summary>
        [Test]
        public void MetacriticRatingTest()
        {
            // TODO unit test for the property 'MetacriticRating'
        }
        /// <summary>
        /// Test the property 'Genres'
        /// </summary>
        [Test]
        public void GenresTest()
        {
            // TODO unit test for the property 'Genres'
        }
        /// <summary>
        /// Test the property 'GenreList'
        /// </summary>
        [Test]
        public void GenreListTest()
        {
            // TODO unit test for the property 'GenreList'
        }
        /// <summary>
        /// Test the property 'Directors'
        /// </summary>
        [Test]
        public void DirectorsTest()
        {
            // TODO unit test for the property 'Directors'
        }
        /// <summary>
        /// Test the property 'DirectorList'
        /// </summary>
        [Test]
        public void DirectorListTest()
        {
            // TODO unit test for the property 'DirectorList'
        }
        /// <summary>
        /// Test the property 'Stars'
        /// </summary>
        [Test]
        public void StarsTest()
        {
            // TODO unit test for the property 'Stars'
        }
        /// <summary>
        /// Test the property 'StarList'
        /// </summary>
        [Test]
        public void StarListTest()
        {
            // TODO unit test for the property 'StarList'
        }

    }

}
