/* 
 * IMDb-API
 *
 * The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>
 *
 * OpenAPI spec version: 1.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
//using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SearchData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SearchDataTests
    {
        // TODO uncomment below to declare an instance variable for SearchData
        //private SearchData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SearchData
            //instance = new SearchData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SearchData
        /// </summary>
        [Test]
        public void SearchDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SearchData
            //Assert.IsInstanceOfType<SearchData> (instance, "variable 'instance' is a SearchData");
        }


        /// <summary>
        /// Test the property 'SearchType'
        /// </summary>
        [Test]
        public void SearchTypeTest()
        {
            // TODO unit test for the property 'SearchType'
        }
        /// <summary>
        /// Test the property 'Expression'
        /// </summary>
        [Test]
        public void ExpressionTest()
        {
            // TODO unit test for the property 'Expression'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }

    }

}
