/* 
 * IMDb-API
 *
 * The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>
 *
 * OpenAPI spec version: 1.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
//using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TitleData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TitleDataTests
    {
        // TODO uncomment below to declare an instance variable for TitleData
        //private TitleData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TitleData
            //instance = new TitleData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TitleData
        /// </summary>
        [Test]
        public void TitleDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TitleData
            //Assert.IsInstanceOfType<TitleData> (instance, "variable 'instance' is a TitleData");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'OriginalTitle'
        /// </summary>
        [Test]
        public void OriginalTitleTest()
        {
            // TODO unit test for the property 'OriginalTitle'
        }
        /// <summary>
        /// Test the property 'FullTitle'
        /// </summary>
        [Test]
        public void FullTitleTest()
        {
            // TODO unit test for the property 'FullTitle'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Test]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'ReleaseDate'
        /// </summary>
        [Test]
        public void ReleaseDateTest()
        {
            // TODO unit test for the property 'ReleaseDate'
        }
        /// <summary>
        /// Test the property 'RuntimeMins'
        /// </summary>
        [Test]
        public void RuntimeMinsTest()
        {
            // TODO unit test for the property 'RuntimeMins'
        }
        /// <summary>
        /// Test the property 'RuntimeStr'
        /// </summary>
        [Test]
        public void RuntimeStrTest()
        {
            // TODO unit test for the property 'RuntimeStr'
        }
        /// <summary>
        /// Test the property 'Plot'
        /// </summary>
        [Test]
        public void PlotTest()
        {
            // TODO unit test for the property 'Plot'
        }
        /// <summary>
        /// Test the property 'PlotLocal'
        /// </summary>
        [Test]
        public void PlotLocalTest()
        {
            // TODO unit test for the property 'PlotLocal'
        }
        /// <summary>
        /// Test the property 'PlotLocalIsRtl'
        /// </summary>
        [Test]
        public void PlotLocalIsRtlTest()
        {
            // TODO unit test for the property 'PlotLocalIsRtl'
        }
        /// <summary>
        /// Test the property 'Awards'
        /// </summary>
        [Test]
        public void AwardsTest()
        {
            // TODO unit test for the property 'Awards'
        }
        /// <summary>
        /// Test the property 'Directors'
        /// </summary>
        [Test]
        public void DirectorsTest()
        {
            // TODO unit test for the property 'Directors'
        }
        /// <summary>
        /// Test the property 'DirectorList'
        /// </summary>
        [Test]
        public void DirectorListTest()
        {
            // TODO unit test for the property 'DirectorList'
        }
        /// <summary>
        /// Test the property 'Writers'
        /// </summary>
        [Test]
        public void WritersTest()
        {
            // TODO unit test for the property 'Writers'
        }
        /// <summary>
        /// Test the property 'WriterList'
        /// </summary>
        [Test]
        public void WriterListTest()
        {
            // TODO unit test for the property 'WriterList'
        }
        /// <summary>
        /// Test the property 'Stars'
        /// </summary>
        [Test]
        public void StarsTest()
        {
            // TODO unit test for the property 'Stars'
        }
        /// <summary>
        /// Test the property 'StarList'
        /// </summary>
        [Test]
        public void StarListTest()
        {
            // TODO unit test for the property 'StarList'
        }
        /// <summary>
        /// Test the property 'ActorList'
        /// </summary>
        [Test]
        public void ActorListTest()
        {
            // TODO unit test for the property 'ActorList'
        }
        /// <summary>
        /// Test the property 'FullCast'
        /// </summary>
        [Test]
        public void FullCastTest()
        {
            // TODO unit test for the property 'FullCast'
        }
        /// <summary>
        /// Test the property 'Genres'
        /// </summary>
        [Test]
        public void GenresTest()
        {
            // TODO unit test for the property 'Genres'
        }
        /// <summary>
        /// Test the property 'GenreList'
        /// </summary>
        [Test]
        public void GenreListTest()
        {
            // TODO unit test for the property 'GenreList'
        }
        /// <summary>
        /// Test the property 'Companies'
        /// </summary>
        [Test]
        public void CompaniesTest()
        {
            // TODO unit test for the property 'Companies'
        }
        /// <summary>
        /// Test the property 'CompanyList'
        /// </summary>
        [Test]
        public void CompanyListTest()
        {
            // TODO unit test for the property 'CompanyList'
        }
        /// <summary>
        /// Test the property 'Countries'
        /// </summary>
        [Test]
        public void CountriesTest()
        {
            // TODO unit test for the property 'Countries'
        }
        /// <summary>
        /// Test the property 'CountryList'
        /// </summary>
        [Test]
        public void CountryListTest()
        {
            // TODO unit test for the property 'CountryList'
        }
        /// <summary>
        /// Test the property 'Languages'
        /// </summary>
        [Test]
        public void LanguagesTest()
        {
            // TODO unit test for the property 'Languages'
        }
        /// <summary>
        /// Test the property 'LanguageList'
        /// </summary>
        [Test]
        public void LanguageListTest()
        {
            // TODO unit test for the property 'LanguageList'
        }
        /// <summary>
        /// Test the property 'ContentRating'
        /// </summary>
        [Test]
        public void ContentRatingTest()
        {
            // TODO unit test for the property 'ContentRating'
        }
        /// <summary>
        /// Test the property 'ImDbRating'
        /// </summary>
        [Test]
        public void ImDbRatingTest()
        {
            // TODO unit test for the property 'ImDbRating'
        }
        /// <summary>
        /// Test the property 'ImDbRatingVotes'
        /// </summary>
        [Test]
        public void ImDbRatingVotesTest()
        {
            // TODO unit test for the property 'ImDbRatingVotes'
        }
        /// <summary>
        /// Test the property 'MetacriticRating'
        /// </summary>
        [Test]
        public void MetacriticRatingTest()
        {
            // TODO unit test for the property 'MetacriticRating'
        }
        /// <summary>
        /// Test the property 'Ratings'
        /// </summary>
        [Test]
        public void RatingsTest()
        {
            // TODO unit test for the property 'Ratings'
        }
        /// <summary>
        /// Test the property 'Wikipedia'
        /// </summary>
        [Test]
        public void WikipediaTest()
        {
            // TODO unit test for the property 'Wikipedia'
        }
        /// <summary>
        /// Test the property 'Posters'
        /// </summary>
        [Test]
        public void PostersTest()
        {
            // TODO unit test for the property 'Posters'
        }
        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Test]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }
        /// <summary>
        /// Test the property 'Trailer'
        /// </summary>
        [Test]
        public void TrailerTest()
        {
            // TODO unit test for the property 'Trailer'
        }
        /// <summary>
        /// Test the property 'BoxOffice'
        /// </summary>
        [Test]
        public void BoxOfficeTest()
        {
            // TODO unit test for the property 'BoxOffice'
        }
        /// <summary>
        /// Test the property 'Tagline'
        /// </summary>
        [Test]
        public void TaglineTest()
        {
            // TODO unit test for the property 'Tagline'
        }
        /// <summary>
        /// Test the property 'Keywords'
        /// </summary>
        [Test]
        public void KeywordsTest()
        {
            // TODO unit test for the property 'Keywords'
        }
        /// <summary>
        /// Test the property 'KeywordList'
        /// </summary>
        [Test]
        public void KeywordListTest()
        {
            // TODO unit test for the property 'KeywordList'
        }
        /// <summary>
        /// Test the property 'Similars'
        /// </summary>
        [Test]
        public void SimilarsTest()
        {
            // TODO unit test for the property 'Similars'
        }
        /// <summary>
        /// Test the property 'TvSeriesInfo'
        /// </summary>
        [Test]
        public void TvSeriesInfoTest()
        {
            // TODO unit test for the property 'TvSeriesInfo'
        }
        /// <summary>
        /// Test the property 'TvEpisodeInfo'
        /// </summary>
        [Test]
        public void TvEpisodeInfoTest()
        {
            // TODO unit test for the property 'TvEpisodeInfo'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }

    }

}
