/* 
 * IMDb-API
 *
 * The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>
 *
 * OpenAPI spec version: 1.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
//using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TvEpisodeInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TvEpisodeInfoTests
    {
        // TODO uncomment below to declare an instance variable for TvEpisodeInfo
        //private TvEpisodeInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TvEpisodeInfo
            //instance = new TvEpisodeInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TvEpisodeInfo
        /// </summary>
        [Test]
        public void TvEpisodeInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TvEpisodeInfo
            //Assert.IsInstanceOfType<TvEpisodeInfo> (instance, "variable 'instance' is a TvEpisodeInfo");
        }


        /// <summary>
        /// Test the property 'SeriesId'
        /// </summary>
        [Test]
        public void SeriesIdTest()
        {
            // TODO unit test for the property 'SeriesId'
        }
        /// <summary>
        /// Test the property 'SeriesTitle'
        /// </summary>
        [Test]
        public void SeriesTitleTest()
        {
            // TODO unit test for the property 'SeriesTitle'
        }
        /// <summary>
        /// Test the property 'SeriesFullTitle'
        /// </summary>
        [Test]
        public void SeriesFullTitleTest()
        {
            // TODO unit test for the property 'SeriesFullTitle'
        }
        /// <summary>
        /// Test the property 'SeriesYear'
        /// </summary>
        [Test]
        public void SeriesYearTest()
        {
            // TODO unit test for the property 'SeriesYear'
        }
        /// <summary>
        /// Test the property 'SeriesYearEnd'
        /// </summary>
        [Test]
        public void SeriesYearEndTest()
        {
            // TODO unit test for the property 'SeriesYearEnd'
        }
        /// <summary>
        /// Test the property 'SeasonNumber'
        /// </summary>
        [Test]
        public void SeasonNumberTest()
        {
            // TODO unit test for the property 'SeasonNumber'
        }
        /// <summary>
        /// Test the property 'EpisodeNumber'
        /// </summary>
        [Test]
        public void EpisodeNumberTest()
        {
            // TODO unit test for the property 'EpisodeNumber'
        }
        /// <summary>
        /// Test the property 'PreviousEpisodeId'
        /// </summary>
        [Test]
        public void PreviousEpisodeIdTest()
        {
            // TODO unit test for the property 'PreviousEpisodeId'
        }
        /// <summary>
        /// Test the property 'NextEpisodeId'
        /// </summary>
        [Test]
        public void NextEpisodeIdTest()
        {
            // TODO unit test for the property 'NextEpisodeId'
        }

    }

}
