/* 
 * IMDb-API
 *
 * The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>
 *
 * OpenAPI spec version: 1.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
//using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TvSeriesInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TvSeriesInfoTests
    {
        // TODO uncomment below to declare an instance variable for TvSeriesInfo
        //private TvSeriesInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TvSeriesInfo
            //instance = new TvSeriesInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TvSeriesInfo
        /// </summary>
        [Test]
        public void TvSeriesInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TvSeriesInfo
            //Assert.IsInstanceOfType<TvSeriesInfo> (instance, "variable 'instance' is a TvSeriesInfo");
        }


        /// <summary>
        /// Test the property 'YearEnd'
        /// </summary>
        [Test]
        public void YearEndTest()
        {
            // TODO unit test for the property 'YearEnd'
        }
        /// <summary>
        /// Test the property 'Creators'
        /// </summary>
        [Test]
        public void CreatorsTest()
        {
            // TODO unit test for the property 'Creators'
        }
        /// <summary>
        /// Test the property 'CreatorList'
        /// </summary>
        [Test]
        public void CreatorListTest()
        {
            // TODO unit test for the property 'CreatorList'
        }
        /// <summary>
        /// Test the property 'Seasons'
        /// </summary>
        [Test]
        public void SeasonsTest()
        {
            // TODO unit test for the property 'Seasons'
        }

    }

}
