/* 
 * IMDb-API
 *
 * The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>
 *
 * OpenAPI spec version: 1.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
//using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserRatingData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserRatingDataTests
    {
        // TODO uncomment below to declare an instance variable for UserRatingData
        //private UserRatingData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserRatingData
            //instance = new UserRatingData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserRatingData
        /// </summary>
        [Test]
        public void UserRatingDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserRatingData
            //Assert.IsInstanceOfType<UserRatingData> (instance, "variable 'instance' is a UserRatingData");
        }


        /// <summary>
        /// Test the property 'ImDbId'
        /// </summary>
        [Test]
        public void ImDbIdTest()
        {
            // TODO unit test for the property 'ImDbId'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'FullTitle'
        /// </summary>
        [Test]
        public void FullTitleTest()
        {
            // TODO unit test for the property 'FullTitle'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Test]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'TotalRating'
        /// </summary>
        [Test]
        public void TotalRatingTest()
        {
            // TODO unit test for the property 'TotalRating'
        }
        /// <summary>
        /// Test the property 'TotalRatingVotes'
        /// </summary>
        [Test]
        public void TotalRatingVotesTest()
        {
            // TODO unit test for the property 'TotalRatingVotes'
        }
        /// <summary>
        /// Test the property 'Ratings'
        /// </summary>
        [Test]
        public void RatingsTest()
        {
            // TODO unit test for the property 'Ratings'
        }
        /// <summary>
        /// Test the property 'DemographicAll'
        /// </summary>
        [Test]
        public void DemographicAllTest()
        {
            // TODO unit test for the property 'DemographicAll'
        }
        /// <summary>
        /// Test the property 'DemographicMales'
        /// </summary>
        [Test]
        public void DemographicMalesTest()
        {
            // TODO unit test for the property 'DemographicMales'
        }
        /// <summary>
        /// Test the property 'DemographicFemales'
        /// </summary>
        [Test]
        public void DemographicFemalesTest()
        {
            // TODO unit test for the property 'DemographicFemales'
        }
        /// <summary>
        /// Test the property 'Top1000Voters'
        /// </summary>
        [Test]
        public void Top1000VotersTest()
        {
            // TODO unit test for the property 'Top1000Voters'
        }
        /// <summary>
        /// Test the property 'UsUsers'
        /// </summary>
        [Test]
        public void UsUsersTest()
        {
            // TODO unit test for the property 'UsUsers'
        }
        /// <summary>
        /// Test the property 'NonUSUsers'
        /// </summary>
        [Test]
        public void NonUSUsersTest()
        {
            // TODO unit test for the property 'NonUSUsers'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }

    }

}
