/* 
 * IMDb-API
 *
 * The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>
 *
 * OpenAPI spec version: 1.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
//using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserRatingDataDemographic
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserRatingDataDemographicTests
    {
        // TODO uncomment below to declare an instance variable for UserRatingDataDemographic
        //private UserRatingDataDemographic instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserRatingDataDemographic
            //instance = new UserRatingDataDemographic();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserRatingDataDemographic
        /// </summary>
        [Test]
        public void UserRatingDataDemographicInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserRatingDataDemographic
            //Assert.IsInstanceOfType<UserRatingDataDemographic> (instance, "variable 'instance' is a UserRatingDataDemographic");
        }


        /// <summary>
        /// Test the property 'AllAges'
        /// </summary>
        [Test]
        public void AllAgesTest()
        {
            // TODO unit test for the property 'AllAges'
        }
        /// <summary>
        /// Test the property 'AgesUnder18'
        /// </summary>
        [Test]
        public void AgesUnder18Test()
        {
            // TODO unit test for the property 'AgesUnder18'
        }
        /// <summary>
        /// Test the property 'Ages18To29'
        /// </summary>
        [Test]
        public void Ages18To29Test()
        {
            // TODO unit test for the property 'Ages18To29'
        }
        /// <summary>
        /// Test the property 'Ages30To44'
        /// </summary>
        [Test]
        public void Ages30To44Test()
        {
            // TODO unit test for the property 'Ages30To44'
        }
        /// <summary>
        /// Test the property 'AgesOver45'
        /// </summary>
        [Test]
        public void AgesOver45Test()
        {
            // TODO unit test for the property 'AgesOver45'
        }

    }

}
